version: '3.7'
services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0-slim-faststart
    environment:
      - ORACLE_RANDOM_PASSWORD=true
    shm_size: 4gb
    deploy:
      resources:
        limits:
          memory: 4gb
        reservations:
          memory: 4gb
    ports:
      - "1521:1521"
    volumes:
      - ./oracle-init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
    container_name: oraclefpsak
